# Generated by Django 3.2.24 on 2024-03-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizkhalifa', '0003_gameinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinformation',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='gameinformation',
            name='options_text',
        ),
        migrations.AddField(
            model_name='gameinformation',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='gameinformation',
            name='option_a',
            field=models.CharField(default='A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameinformation',
            name='option_b',
            field=models.CharField(default='B', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameinformation',
            name='option_c',
            field=models.CharField(default='C', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameinformation',
            name='option_d',
            field=models.CharField(default='D', max_length=255),
            preserve_default=False,
        ),
    ]
